import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  kennisbank: [
    {
      type: "category",
      label: "API Ontwikkeling",
      link: { type: "doc", id: "api-ontwikkeling/index" },
      items: [{ type: "autogenerated", dirName: "api-ontwikkeling" }],
    },
    {
      type: "category",
      label: "Front-end",
      link: { type: "doc", id: "front-end/index" },
      items: [{ type: "autogenerated", dirName: "front-end" }],
    },
    {
      type: "category",
      label: "Data & Interoperabiliteit",
      link: { type: "doc", id: "data/index" },
      items: [{ type: "autogenerated", dirName: "data" }],
    },
    {
      type: "category",
      label: "Open Source",
      link: { type: "doc", id: "open-source/index" },
      items: [{ type: "autogenerated", dirName: "open-source" }],
    },
    {
      type: "category",
      label: "DevOps & Platform",
      link: { type: "doc", id: "devops/index" },
      items: [{ type: "autogenerated", dirName: "devops" }],
    },
    {
      type: "category",
      label: "Security",
      link: { type: "doc", id: "security/index" },
      items: [{ type: "autogenerated", dirName: "security" }],
    },
    {
      type: "category",
      label: "Leidraad softwareontwikkeling",
      link: { type: "doc", id: "leidraad/index" },
      items: [{ type: "autogenerated", dirName: "leidraad" }],
    },
    {
      type: "category",
      label: "MijnServices",
      link: { type: "doc", id: "mijnservices/index" },
      items: [{ type: "autogenerated", dirName: "mijnservices" }],
    },
  ],
  "mijn-services": [
    {
      type: "category",
      label: "MijnServices",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "autogenerated",
          dirName: "mijnservices",
        },
      ],
    },
  ],
};

export default sidebars;
